# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY . /app

# Install dependencies
# Using pip and pyproject.toml / requirements.txt
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

# Expose the port (optional, though not strictly necessary for MCP servers using stdio)
EXPOSE 8000

# Default command
CMD ["python", "biorxiv_server.py"]
